# Generated by Django 2.2 on 2022-01-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='query',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
