# Generated by Django 2.2 on 2022-01-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator_app', '0003_auto_20220103_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='query',
            field=models.IntegerField(),
        ),
    ]
