# Generated by Django 2.2 on 2022-01-03 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator_app', '0004_auto_20220103_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_aggregator_app.NewsQuery'),
        ),
    ]
